const bcrypt = require('bcryptjs');
const data = {
	users: [
		{
			name: 'John',
			email: 'admin@example.com',
			password: bcrypt.hashSync('123456'),
			isAdmin: true,
		},
		{
			name: 'Jane',
			email: 'user@example.com',
			password: bcrypt.hashSync('123456'),
			isAdmin: false,
		},
	],
	products: [
		{
			name: 'Free Shirt',
			slug: 'free-shirt',
			category: 'Shirts',
			image: '/assets/images/shirt2.jpg',
			isFeatured: true,
			featuredImage: '/assets/images/banner1.jpg',
			price: 70,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: 'A popular shirt',
		},
		{
			name: 'Fit Shirt',
			slug: 'fit-shirt',
			category: 'Shirts',
			image: '/assets/images/shirt1.jpg',
			isFeatured: true,
			featuredImage: '/assets/images/banner2.jpg',
			price: 80,
			brand: 'Adidas',
			rating: 4.2,
			numReviews: 10,
			countInStock: 20,
			description: 'A popular shirt',
		},
		{
			name: 'Slim Shirt',
			slug: 'slim-shirt',
			category: 'Shirts',
			image: '/assets/images/shirt3.jpg',
			price: 90,
			brand: 'Raymond',
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: 'A popular shirt',
		},
		{
			name: 'Golf Pants',
			slug: 'golf-pants',
			category: 'Pants',
			image: '/assets/images/pant1.jpg',
			price: 90,
			brand: 'Oliver',
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: 'Smart looking pants',
		},
		{
			name: 'Fit Pants',
			slug: 'fit-pants',
			category: 'Pants',
			image: '/assets/images/pant2.jpg',
			price: 95,
			brand: 'Zara',
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: 'A popular pants',
		},
		{
			name: 'Classic Pants',
			slug: 'classic-pants',
			category: 'Pants',
			image: '/assets/images/pants3.jpg',
			price: 75,
			brand: 'Casely',
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: 'A popular pants',
		},
	],
};
module.exports = data;
